export const assets = {
  logo: "https://geminimotorsgoa.in/assets/gemini-logo-transparent-C33UAXGI.png",
  hero: "https://geminimotorsgoa.in/assets/dost-xl-hero-replacement-CaWcp0BF.png",
  lcv: "https://geminimotorsgoa.in/assets/dost_xl_exterior-Dv2YKi5a.jpg",
  badaDost: "https://geminimotorsgoa.in/assets/bada-dost-i5-plus-card-dAAsFsCH.png",
  mhcv: "https://geminimotorsgoa.in/assets/avtr_4625h_la_studio_exterior-qjuH9euD.jpg",
  tipper: "https://geminimotorsgoa.in/assets/tipper_8x4_highway_exterior-D9TGlshm.jpg",
  finance: "https://geminimotorsgoa.in/assets/business_journey-BA16Icwh.jpg",
  service: "https://geminimotorsgoa.in/assets/avtr_4625h_la_chassis_product_view-BwgyHqyj.jpg",
  green: "https://geminimotorsgoa.in/assets/sustainable_growth-DUjsWNQd.jpg",
  iev3: "https://geminimotorsgoa.in/assets/switch_iev3_hero-Co1epeV6.jpg",
  iev4: "https://geminimotorsgoa.in/assets/switch_iev4_hero-DDjf850G.jpg",
  iev4Tipper: "https://geminimotorsgoa.in/assets/switch_iev4_garbage_hero-DnQ0yFbj.jpg",
};

const makeProducts = (brand, type, prefix, models, image, use) =>
  models.map(([name, slug]) => ({
    id: slug,
    name,
    brand,
    type,
    image,
    use,
    path: `${prefix}${slug}/`,
  }));

const officialSources = {
  taurusHippo:
    "https://www.ashokleyland.com/in/pressrelease/ashok-leyland-reintroduces-iconic-taurus-and-hippo-heavy-duty-trucks",
  airSuspension:
    "https://www.ashokleyland.com/in/pressrelease/ashok-leyland-introduces-indias-first-air-suspension-range-of-trucks-with-best-in-class-payload-capability",
  genuineParts: "https://www.ashokleyland.com/in/genuine-parts",
  aftermarket: "https://www.ashokleyland.com/in/aftermarket",
  switchIev3: "https://www.switchmobilityev.com/iev-series-iev3",
  switchIev4: "https://www.switchmobilityev.com/iev-series-iev4",
};

const lightProducts = makeProducts(
  "Ashok Leyland",
  "LCV",
  "/commercial/light/",
  [
    ["Gemini L-Series 2.5T", "gemini-l-series-25t"],
    ["Bada Dost CNG", "bada-dost-cng"],
    ["Bada Dost i2", "bada-dost-i2"],
    ["Bada Dost i3+", "bada-dost-i3-plus"],
    ["Bada Dost i3+ with LNT", "bada-dost-i3-plus-with-lnt"],
    ["Bada Dost i3+ XL", "bada-dost-i3-plus-xl"],
    ["Bada Dost i4", "bada-dost-i4"],
    ["Bada Dost i5", "bada-dost-i5"],
    ["Bada Dost i5+", "bada-dost-i5-plus"],
    ["Bada Dost i5 XL", "bada-dost-i5-xl"],
    ["Bada Dost i6", "bada-dost-i6"],
    ["DOST CNG", "dost-cng"],
    ["DOST + XL", "dost-plus-xl"],
    ["DOST + XL CNG", "dost-plus-xl-cng"],
    ["DOST + XL Twin Fuel", "dost-plus-xl-twin-fuel"],
    ["DOST Twin Fuel", "dost-twin-fuel"],
    ["DOST XL", "dost-xl"],
    ["Saathi", "saathi"],
    ["Partner 4 Tyre", "partner-4-tyre"],
    ["Partner 6 Tyre", "partner-6-tyre"],
    ["Partner Municipal", "partner-municipal"],
    ["MiTR Ambulance", "mitr-ambulance"],
    ["MiTR School Bus", "mitr-school-bus"],
    ["MiTR Staff Bus", "mitr-staff-bus"],
  ],
  assets.lcv,
  "City delivery, retail and business routes",
);

const heavyProducts = makeProducts(
  "Ashok Leyland",
  "M&HCV",
  "/commercial/medium-heavy/",
  [
    ["AVTR 4625H LA", "avtr-4625h-la"],
    ["AVTR 4525H DTLA", "avtr-4525h-dtla"],
    ["AVTR 4925H DTLA", "avtr-4925h-dtla"],
    ["AVTR 10X2", "avtr-10x2"],
    ["10X2 / 48T", "10x2-gvw-48t"],
    ["10X2 Tipper", "10x2-tipper"],
    ["10X4 Tipper", "10x4-tipper"],
    ["8X4 Tipper", "8x4-tipper"],
    ["8X2 / 35T", "8x2-gvw-35t"],
    ["6X4 Tractor", "6x4-tractor"],
    ["6X2 / 26-31T", "6x2-gvw-26t-31t"],
    ["4X2 / 19T", "4x2-gvw-19t"],
    ["4X2 with 2-axle trailer", "4x2-with-2-axle-trailer"],
    ["4X2 with 3-axle trailer", "4x2-with-3-axle-trailer"],
    ["Transit Mixer", "transit-mixer"],
    ["Boom Pump", "boom-pump"],
    ["BOSS", "boss"],
    ["BOSS 1115 HE", "boss-1115-he"],
    ["Partner Super", "partner-super"],
    ["ecomet STAR", "ecomet-star"],
    ["ICV Tippers", "icv-tippers"],
  ],
  assets.mhcv,
  "Fleet, haulage and construction work",
);

const latestAshokProducts = [
  {
    id: "ashok-taurus",
    name: "TAURUS",
    brand: "Ashok Leyland",
    type: "M&HCV",
    image: assets.tipper,
    use: "Official heavy-duty tipper range — confirm Goa availability",
    url: officialSources.taurusHippo,
    source: "Official 2026 range",
  },
  {
    id: "ashok-hippo",
    name: "HIPPO",
    brand: "Ashok Leyland",
    type: "M&HCV",
    image: assets.mhcv,
    use: "Official heavy-duty tractor range — confirm Goa availability",
    url: officialSources.taurusHippo,
    source: "Official 2026 range",
  },
  {
    id: "avtr-4925-10x2-mav",
    name: "AVTR 4925 10x2 MAV",
    brand: "Ashok Leyland",
    type: "M&HCV",
    image: assets.mhcv,
    use: "Official air-suspension 49T truck — confirm Goa availability",
    url: officialSources.airSuspension,
    source: "Official 2026 range",
  },
  {
    id: "avtr-4625-10x2-mav",
    name: "AVTR 4625 10x2 MAV",
    brand: "Ashok Leyland",
    type: "M&HCV",
    image: assets.mhcv,
    use: "Official air-suspension 46T truck — confirm Goa availability",
    url: officialSources.airSuspension,
    source: "Official 2026 range",
  },
  {
    id: "avtr-4525-8x2-mav",
    name: "AVTR 4525 8x2 MAV",
    brand: "Ashok Leyland",
    type: "M&HCV",
    image: assets.mhcv,
    use: "Official air-suspension 45T truck — confirm Goa availability",
    url: officialSources.airSuspension,
    source: "Official 2026 range",
  },
];

const evProducts = [
  {
    id: "switch-iev3",
    name: "SWITCH IeV3",
    brand: "SWITCH Mobility",
    type: "EV",
    image: assets.iev3,
    use: "Electric last-mile delivery",
    path: "/electric-mobility/switch-iev3/",
  },
  {
    id: "switch-iev4",
    name: "SWITCH IeV4",
    brand: "SWITCH Mobility",
    type: "EV",
    image: assets.iev4,
    use: "Electric commercial transport",
    path: "/electric-mobility/switch-iev4/",
  },
  {
    id: "switch-iev4-garbage-tipper",
    name: "SWITCH IeV4 Garbage Tipper",
    brand: "SWITCH Mobility",
    type: "EV",
    image: assets.iev4Tipper,
    use: "Municipal and waste collection",
    path: "/electric-mobility/switch-iev4-garbage-tipper/",
  },
];

const switchConfigurations = [
  {
    id: "switch-iev3-standard",
    name: "SWITCH IeV3 Standard",
    brand: "SWITCH Mobility",
    type: "EV",
    image: assets.iev3,
    use: "Official IeV3 body configuration — confirm Goa availability",
    url: officialSources.switchIev3,
    source: "Official configuration",
  },
  {
    id: "switch-iev3-container",
    name: "SWITCH IeV3 Container",
    brand: "SWITCH Mobility",
    type: "EV",
    image: assets.iev3,
    use: "Official IeV3 cargo-body configuration — confirm Goa availability",
    url: officialSources.switchIev3,
    source: "Official configuration",
  },
  {
    id: "switch-iev3-tipper",
    name: "SWITCH IeV3 Tipper",
    brand: "SWITCH Mobility",
    type: "EV",
    image: assets.iev3,
    use: "Official IeV3 tipper configuration — confirm Goa availability",
    url: officialSources.switchIev3,
    source: "Official configuration",
  },
  {
    id: "switch-iev4-standard",
    name: "SWITCH IeV4 Standard",
    brand: "SWITCH Mobility",
    type: "EV",
    image: assets.iev4,
    use: "Official IeV4 body configuration — confirm Goa availability",
    url: officialSources.switchIev4,
    source: "Official configuration",
  },
  {
    id: "switch-iev4-container",
    name: "SWITCH IeV4 Container",
    brand: "SWITCH Mobility",
    type: "EV",
    image: assets.iev4,
    use: "Official IeV4 cargo-body configuration — confirm Goa availability",
    url: officialSources.switchIev4,
    source: "Official configuration",
  },
  {
    id: "switch-iev4-reefer",
    name: "SWITCH IeV4 Reefer",
    brand: "SWITCH Mobility",
    type: "EV",
    image: assets.iev4,
    use: "Official IeV4 reefer configuration — confirm Goa availability",
    url: officialSources.switchIev4,
    source: "Official configuration",
  },
];

export const sparePartsRange = [
  {
    id: "leyparts",
    name: "LEYPARTS® Genuine Parts",
    brand: "Ashok Leyland",
    description: "Premium spare parts designed and tested for Ashok Leyland vehicles.",
    request: "LEYPARTS® Genuine Parts",
    sourceUrl: officialSources.genuineParts,
  },
  {
    id: "valueparts",
    name: "VALUEPARTS",
    brand: "Ashok Leyland",
    description: "Official economical aftermarket parts range; compatibility is checked at enquiry.",
    request: "VALUEPARTS",
    sourceUrl: officialSources.genuineParts,
  },
  {
    id: "trailer-axle-suspension-kit",
    name: "Trailer Axle Suspension Kit",
    brand: "Ashok Leyland",
    description: "Ask about the official custom-made kit for your trailer application.",
    request: "Trailer Axle Suspension Kit",
    sourceUrl: officialSources.aftermarket,
  },
  {
    id: "repair-kit",
    name: "Repair Kit",
    brand: "Ashok Leyland",
    description: "Request an official repair-kit match using your vehicle and part details.",
    request: "Repair Kit",
    sourceUrl: officialSources.aftermarket,
  },
  {
    id: "retrofitment-kit",
    name: "Retrofitment Kit",
    brand: "Ashok Leyland",
    description: "Discuss an official retrofitment-kit requirement with the parts team.",
    request: "Retrofitment Kit",
    sourceUrl: officialSources.aftermarket,
  },
  {
    id: "al-recon",
    name: "AL Recon",
    brand: "Ashok Leyland",
    description: "Ask the team to check availability of ready-to-fit reconditioned products.",
    request: "AL Recon availability check",
    sourceUrl: officialSources.aftermarket,
  },
  {
    id: "leykart-match",
    name: "LEYKART® Parts Match",
    brand: "Ashok Leyland",
    description: "Use a part number, vehicle number, chassis number or model to identify a match.",
    request: "LEYKART® assisted parts match",
    sourceUrl: officialSources.genuineParts,
  },
  {
    id: "switch-ev-parts",
    name: "SWITCH EV Parts Support",
    brand: "SWITCH Mobility",
    description: "Share the vehicle model and VIN for EV aggregate or charging-system support.",
    request: "SWITCH Mobility EV parts support",
  },
];

export const catalogue = [
  ...latestAshokProducts,
  ...lightProducts,
  ...heavyProducts,
  ...evProducts,
  ...switchConfigurations,
];
export const evRange = [...evProducts, ...switchConfigurations];
